/* Generated by app/build.py from the lesson files – do not edit by hand.
   After adding a lesson, run `python3 app/build.py` and commit this file. */
var LESSON_LIST = [
 {
  "id": "grade-6/bridging-w1-l1",
  "grade": 6,
  "course": "bridging",
  "week": 1,
  "title": "Data Quality and AI Outputs",
  "activities": 11
 },
 {
  "id": "grade-6/main-w1-l1",
  "grade": 6,
  "course": "main",
  "week": 1,
  "title": "Rule-Based vs Learning Systems + Hands-On Exploration",
  "activities": 22
 },
 {
  "id": "grade-7/main-w1-l1",
  "grade": 7,
  "course": "main",
  "week": 1,
  "title": "How Models Learn + AI as a Workflow",
  "activities": 18
 },
 {
  "id": "grade-8/main-w1-l1",
  "grade": 8,
  "course": "main",
  "week": 1,
  "title": "From ‘It Works’ to ‘How Well’ + Two Outputs, One Verdict",
  "activities": 25
 },
 {
  "id": "grade-8/main-w2-l1",
  "grade": 8,
  "course": "main",
  "week": 2,
  "title": "Inside the Pipeline + Change One Factor",
  "activities": 19
 },
 {
  "id": "grade-9/bridging-w1-l1",
  "grade": 9,
  "course": "bridging",
  "week": 1,
  "title": "Comparing Approaches",
  "activities": 12
 },
 {
  "id": "grade-9/main-w1-l1",
  "grade": 9,
  "course": "main",
  "week": 1,
  "title": "Open the Black Box + Change One Thing",
  "activities": 19
 },
 {
  "id": "grade-10/bridging-w1-l1",
  "grade": 10,
  "course": "bridging",
  "week": 1,
  "title": "Design Choices Shape the Output",
  "activities": 9
 },
 {
  "id": "grade-10/main-w1-l1",
  "grade": 10,
  "course": "main",
  "week": 1,
  "title": "See the Whole System + Compare, Map, and Stress-Test",
  "activities": 15
 },
 {
  "id": "grade-11/bridging-w1-l1",
  "grade": 11,
  "course": "bridging",
  "week": 1,
  "title": "Evaluating how design shapes performance and reliability",
  "activities": 9
 },
 {
  "id": "grade-11/main-w1-l1",
  "grade": 11,
  "course": "main",
  "week": 1,
  "title": "Optimising AI Solutions for Performance",
  "activities": 14
 },
 {
  "id": "grade-12/bridging-w1-l1",
  "grade": 12,
  "course": "bridging",
  "week": 1,
  "title": "Evaluating trade-offs across accuracy, efficiency, usability and reliability",
  "activities": 11
 },
 {
  "id": "grade-12/main-w1-l1",
  "grade": 12,
  "course": "main",
  "week": 1,
  "title": "Designing AI Systems for Strategic Use",
  "activities": 16
 }
];
if (typeof module !== 'undefined') module.exports = LESSON_LIST;
