/* Generated by app/build.py from the lesson files – do not edit by hand.
   After adding a lesson, run `python3 app/build.py` and commit this file. */
var LESSON_LIST = [
 {
  "id": "grade-6/bridging-w1-l1",
  "grade": 6,
  "course": "bridging",
  "week": 1,
  "title": "Data Quality and AI Outputs",
  "activities": 11
 },
 {
  "id": "grade-6/main-w1-l1",
  "grade": 6,
  "course": "main",
  "week": 1,
  "title": "Rule-Based vs Learning Systems + Hands-On Exploration",
  "activities": 22
 },
 {
  "id": "grade-6/main-w2-l1",
  "grade": 6,
  "course": "main",
  "week": 2,
  "title": "Rules vs Learning: How Each System Works + Train a Simple Model",
  "activities": 23
 },
 {
  "id": "grade-6/main-w3-l1",
  "grade": 6,
  "course": "main",
  "week": 3,
  "title": "Structured Prompts to Complete a Task + Prompt-to-Task Workshop",
  "activities": 25
 },
 {
  "id": "grade-6/main-w4-l1",
  "grade": 6,
  "course": "main",
  "week": 4,
  "title": "Judging Outputs: Correct, Incorrect, Unclear + Output Triage Clinic",
  "activities": 21
 },
 {
  "id": "grade-6/main-w5-l1",
  "grade": 6,
  "course": "main",
  "week": 5,
  "title": "Risks and Responsible Use + Class AI Risk Audit",
  "activities": 24
 },
 {
  "id": "grade-6/main-w6-l1",
  "grade": 6,
  "course": "main",
  "week": 6,
  "title": "Bringing the Strands Together + Integrated Build-and-Check",
  "activities": 24
 },
 {
  "id": "grade-6/main-w7-l1",
  "grade": 6,
  "course": "main",
  "week": 7,
  "title": "Signature Solution: Planning + Prototype and Pressure-Test the Plan",
  "activities": 24
 },
 {
  "id": "grade-6/main-w8-l1",
  "grade": 6,
  "course": "main",
  "week": 8,
  "title": "Signature Solution: Building + Extended Build and Evaluation",
  "activities": 26
 },
 {
  "id": "grade-6/main-w9-l1",
  "grade": 6,
  "course": "main",
  "week": 9,
  "title": "Signature Solution: Refining & Finishing + Final Iteration and Risk Review",
  "activities": 24
 },
 {
  "id": "grade-6/main-w10-l1",
  "grade": 6,
  "course": "main",
  "week": 10,
  "title": "Showcase, Assessment & Reflection + Showcase Carousel and Reflection",
  "activities": 29
 },
 {
  "id": "grade-7/main-w1-l1",
  "grade": 7,
  "course": "main",
  "week": 1,
  "title": "How Models Learn + AI as a Workflow",
  "activities": 18
 },
 {
  "id": "grade-7/main-w2-l1",
  "grade": 7,
  "course": "main",
  "week": 2,
  "title": "The Three-Stage Shape + Build, Trace and Test a Workflow",
  "activities": 26
 },
 {
  "id": "grade-7/main-w3-l1",
  "grade": 7,
  "course": "main",
  "week": 3,
  "title": "Building a Workflow + Test, Fix and Chain",
  "activities": 26
 },
 {
  "id": "grade-7/main-w4-l1",
  "grade": 7,
  "course": "main",
  "week": 4,
  "title": "Judging Outputs + The Evaluation Clinic",
  "activities": 27
 },
 {
  "id": "grade-7/main-w5-l1",
  "grade": 7,
  "course": "main",
  "week": 5,
  "title": "Spotting the Risks + The Risk Audit",
  "activities": 27
 },
 {
  "id": "grade-7/main-w6-l1",
  "grade": 7,
  "course": "main",
  "week": 6,
  "title": "Four Strands, One Task + The Full Run",
  "activities": 28
 },
 {
  "id": "grade-7/main-w7-l1",
  "grade": 7,
  "course": "main",
  "week": 7,
  "title": "Architect First, Build Second + Run It, Break It, Make It Safer",
  "activities": 27
 },
 {
  "id": "grade-7/main-w8-l1",
  "grade": 7,
  "course": "main",
  "week": 8,
  "title": "Build, Evaluate, Improve + Finish It, Then Prove It",
  "activities": 29
 },
 {
  "id": "grade-7/main-w9-l1",
  "grade": 7,
  "course": "main",
  "week": 9,
  "title": "Refining & Finishing + Lock It & Rehearse",
  "activities": 27
 },
 {
  "id": "grade-7/main-w10-l1",
  "grade": 7,
  "course": "main",
  "week": 10,
  "title": "Showcase & Reflection + Peer Review & Stress-Test",
  "activities": 29
 },
 {
  "id": "grade-8/main-w1-l1",
  "grade": 8,
  "course": "main",
  "week": 1,
  "title": "From ‘It Works’ to ‘How Well’ + Two Outputs, One Verdict",
  "activities": 25
 },
 {
  "id": "grade-8/main-w2-l1",
  "grade": 8,
  "course": "main",
  "week": 2,
  "title": "Inside the Pipeline + Change One Factor",
  "activities": 19
 },
 {
  "id": "grade-8/main-w3-l1",
  "grade": 8,
  "course": "main",
  "week": 3,
  "title": "Design the Workflow + Build, Test, Improve",
  "activities": 24
 },
 {
  "id": "grade-8/main-w4-l1",
  "grade": 8,
  "course": "main",
  "week": 4,
  "title": "Judge with Criteria + The Evaluation Clinic",
  "activities": 24
 },
 {
  "id": "grade-8/main-w5-l1",
  "grade": 8,
  "course": "main",
  "week": 5,
  "title": "Accurate Is Not Ethical + The Ethics Audit",
  "activities": 24
 },
 {
  "id": "grade-8/main-w6-l1",
  "grade": 8,
  "course": "main",
  "week": 6,
  "title": "One Model, Four Strands + Run It End to End",
  "activities": 23
 },
 {
  "id": "grade-8/main-w7-l1",
  "grade": 8,
  "course": "main",
  "week": 7,
  "title": "Architect the Plan + Prototype and Pressure-Test",
  "activities": 25
 },
 {
  "id": "grade-8/main-w8-l1",
  "grade": 8,
  "course": "main",
  "week": 8,
  "title": "The Build Loop + The Evaluation Log",
  "activities": 28
 },
 {
  "id": "grade-8/main-w9-l1",
  "grade": 8,
  "course": "main",
  "week": 9,
  "title": "Refining and Finishing + Lock It and Show It",
  "activities": 26
 },
 {
  "id": "grade-8/main-w10-l1",
  "grade": 8,
  "course": "main",
  "week": 10,
  "title": "Showcase and Reflect + Review, Measure, Aim",
  "activities": 29
 },
 {
  "id": "grade-9/bridging-w1-l1",
  "grade": 9,
  "course": "bridging",
  "week": 1,
  "title": "Comparing Approaches",
  "activities": 12
 },
 {
  "id": "grade-9/main-w1-l1",
  "grade": 9,
  "course": "main",
  "week": 1,
  "title": "Open the Black Box + Change One Thing",
  "activities": 19
 },
 {
  "id": "grade-9/main-w2-l1",
  "grade": 9,
  "course": "main",
  "week": 2,
  "title": "Understanding the System + Test the System",
  "activities": 27
 },
 {
  "id": "grade-9/main-w3-l1",
  "grade": 9,
  "course": "main",
  "week": 3,
  "title": "Designing a Solution + Build, Test, Chain",
  "activities": 27
 },
 {
  "id": "grade-9/main-w4-l1",
  "grade": 9,
  "course": "main",
  "week": 4,
  "title": "Judging Outputs + The Evaluation Clinic",
  "activities": 24
 },
 {
  "id": "grade-9/main-w5-l1",
  "grade": 9,
  "course": "main",
  "week": 5,
  "title": "Risk Is a System Property + Auditing the Risks",
  "activities": 25
 },
 {
  "id": "grade-9/main-w6-l1",
  "grade": 9,
  "course": "main",
  "week": 6,
  "title": "Four Strands, One Workflow + Running It End-to-End",
  "activities": 26
 },
 {
  "id": "grade-9/main-w7-l1",
  "grade": 9,
  "course": "main",
  "week": 7,
  "title": "Designing the System + Prototype and Pressure-Test",
  "activities": 26
 },
 {
  "id": "grade-9/main-w8-l1",
  "grade": 9,
  "course": "main",
  "week": 8,
  "title": "Assemble, Evaluate, Refine + Test, Log, Iterate",
  "activities": 28
 },
 {
  "id": "grade-9/main-w9-l1",
  "grade": 9,
  "course": "main",
  "week": 9,
  "title": "Refining & Finishing the System + Lock It & Rehearse the Demo",
  "activities": 27
 },
 {
  "id": "grade-9/main-w10-l1",
  "grade": 9,
  "course": "main",
  "week": 10,
  "title": "Showcase, Assess & Reflect + Peer Review & Aim Higher",
  "activities": 29
 },
 {
  "id": "grade-10/bridging-w1-l1",
  "grade": 10,
  "course": "bridging",
  "week": 1,
  "title": "Design Choices Shape the Output",
  "activities": 9
 },
 {
  "id": "grade-10/main-w1-l1",
  "grade": 10,
  "course": "main",
  "week": 1,
  "title": "See the Whole System + Compare, Map, and Stress-Test",
  "activities": 15
 },
 {
  "id": "grade-10/main-w2-l1",
  "grade": 10,
  "course": "main",
  "week": 2,
  "title": "Understanding the System + Trace, Change, Compare",
  "activities": 22
 },
 {
  "id": "grade-10/main-w3-l1",
  "grade": 10,
  "course": "main",
  "week": 3,
  "title": "Designing a Solution + Build, Test, Improve",
  "activities": 25
 },
 {
  "id": "grade-10/main-w4-l1",
  "grade": 10,
  "course": "main",
  "week": 4,
  "title": "Judging & Improving Outputs + The Evaluation Clinic",
  "activities": 19
 },
 {
  "id": "grade-10/main-w5-l1",
  "grade": 10,
  "course": "main",
  "week": 5,
  "title": "Locate the Risk in the System + Measure the Risk and Govern It",
  "activities": 19
 },
 {
  "id": "grade-10/main-w6-l1",
  "grade": 10,
  "course": "main",
  "week": 6,
  "title": "Bringing the Strands Together + Run It End-to-End",
  "activities": 28
 },
 {
  "id": "grade-10/main-w7-l1",
  "grade": 10,
  "course": "main",
  "week": 7,
  "title": "Architect Your Signature Solution + Prototype and Pressure-Test",
  "activities": 27
 },
 {
  "id": "grade-10/main-w8-l1",
  "grade": 10,
  "course": "main",
  "week": 8,
  "title": "Build, Evaluate, Improve + Finish It, Then Prove It",
  "activities": 17
 },
 {
  "id": "grade-10/main-w9-l1",
  "grade": 10,
  "course": "main",
  "week": 9,
  "title": "Refining & Finishing the System + Lock It and Rehearse the Demo",
  "activities": 24
 },
 {
  "id": "grade-10/main-w10-l1",
  "grade": 10,
  "course": "main",
  "week": 10,
  "title": "Showcase & Reflection + Peer Review & Aim Higher",
  "activities": 24
 },
 {
  "id": "grade-11/bridging-w1-l1",
  "grade": 11,
  "course": "bridging",
  "week": 1,
  "title": "Evaluating how design shapes performance and reliability",
  "activities": 9
 },
 {
  "id": "grade-11/main-w1-l1",
  "grade": 11,
  "course": "main",
  "week": 1,
  "title": "Optimising AI Solutions for Performance",
  "activities": 14
 },
 {
  "id": "grade-11/main-w2-l1",
  "grade": 11,
  "course": "main",
  "week": 2,
  "title": "Understanding the System",
  "activities": 18
 },
 {
  "id": "grade-11/main-w3-l1",
  "grade": 11,
  "course": "main",
  "week": 3,
  "title": "Designing a Solution",
  "activities": 27
 },
 {
  "id": "grade-11/main-w4-l1",
  "grade": 11,
  "course": "main",
  "week": 4,
  "title": "Judging Outputs",
  "activities": 16
 },
 {
  "id": "grade-11/main-w5-l1",
  "grade": 11,
  "course": "main",
  "week": 5,
  "title": "Risks, Ethics & Responsible Use",
  "activities": 18
 },
 {
  "id": "grade-11/main-w6-l1",
  "grade": 11,
  "course": "main",
  "week": 6,
  "title": "Bringing the Strands Together",
  "activities": 28
 },
 {
  "id": "grade-11/main-w7-l1",
  "grade": 11,
  "course": "main",
  "week": 7,
  "title": "Architect Your Signature Solution + Prototype and Pressure-Test",
  "activities": 26
 },
 {
  "id": "grade-11/main-w8-l1",
  "grade": 11,
  "course": "main",
  "week": 8,
  "title": "Build, Evaluate, Improve",
  "activities": 17
 },
 {
  "id": "grade-11/main-w9-l1",
  "grade": 11,
  "course": "main",
  "week": 9,
  "title": "Refining and Finishing + Lock It and Rehearse",
  "activities": 24
 },
 {
  "id": "grade-11/main-w10-l1",
  "grade": 11,
  "course": "main",
  "week": 10,
  "title": "Showcase and Reflection",
  "activities": 24
 },
 {
  "id": "grade-12/bridging-w1-l1",
  "grade": 12,
  "course": "bridging",
  "week": 1,
  "title": "Evaluating trade-offs across accuracy, efficiency, usability and reliability",
  "activities": 11
 },
 {
  "id": "grade-12/main-w1-l1",
  "grade": 12,
  "course": "main",
  "week": 1,
  "title": "Designing AI Systems for Strategic Use",
  "activities": 16
 },
 {
  "id": "grade-12/main-w2-l1",
  "grade": 12,
  "course": "main",
  "week": 2,
  "title": "Understanding the System",
  "activities": 16
 },
 {
  "id": "grade-12/main-w3-l1",
  "grade": 12,
  "course": "main",
  "week": 3,
  "title": "Designing a Solution",
  "activities": 29
 },
 {
  "id": "grade-12/main-w4-l1",
  "grade": 12,
  "course": "main",
  "week": 4,
  "title": "Judging Outputs",
  "activities": 16
 },
 {
  "id": "grade-12/main-w5-l1",
  "grade": 12,
  "course": "main",
  "week": 5,
  "title": "Risks, Ethics & Societal Impact",
  "activities": 20
 },
 {
  "id": "grade-12/main-w6-l1",
  "grade": 12,
  "course": "main",
  "week": 6,
  "title": "Bringing the Strands Together",
  "activities": 23
 },
 {
  "id": "grade-12/main-w7-l1",
  "grade": 12,
  "course": "main",
  "week": 7,
  "title": "Architect Your Signature System + Prototype and Pressure-Test",
  "activities": 23
 },
 {
  "id": "grade-12/main-w8-l1",
  "grade": 12,
  "course": "main",
  "week": 8,
  "title": "Build to Your Plan",
  "activities": 18
 },
 {
  "id": "grade-12/main-w9-l1",
  "grade": 12,
  "course": "main",
  "week": 9,
  "title": "Refining and Explainability + Lock the Architecture and Rehearse",
  "activities": 26
 },
 {
  "id": "grade-12/main-w10-l1",
  "grade": 12,
  "course": "main",
  "week": 10,
  "title": "Showcase and Reflection",
  "activities": 25
 }
];
if (typeof module !== 'undefined') module.exports = LESSON_LIST;
