#!/usr/bin/env python3
"""Builds app/build/ for `clasp push`: the Apps Script source plus a copy of
every page of the public site (index, calendar and each lesson).

Also writes lessons.js at the top of the repository – the lesson list the home
page and the calendar read. After adding a lesson, run this script and commit
lessons.js so the public site lists it too."""
import base64, glob, html as H, json, os, re, shutil
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'app', 'build')

def read(p):
    return open(os.path.join(ROOT, p), encoding='utf-8').read()

# ---- the lesson list: one source of truth, taken from the lesson files ----------
def plain(x):
    return re.sub(r'\s+', ' ', H.unescape(re.sub(r'<[^>]+>', ' ', x))).strip()

def lesson_list():
    out = []
    for p in sorted(glob.glob('grade-*/*.html', root_dir=ROOT)):
        m = re.match(r'grade-(\d+)/(main|bridging)-w(\d+)', p)
        if not m:
            continue
        src = read(p)
        h1 = re.search(r'<h1[^>]*>(.*?)</h1>', src, re.S)          # the lesson's own heading
        t = re.search(r'<title>([^<]*)</title>', src)
        title = plain(h1.group(1)) if h1 else (re.sub(r'\s+–\s+Grade.*$', '', t[1]) if t else p)
        out.append({'id': p[:-5], 'grade': int(m[1]), 'course': m[2], 'week': int(m[3]), 'title': title,
                    'activities': len(re.findall(r'^ \{id:"', src, re.M))})
    return sorted(out, key=lambda l: (l['grade'], l['course'] != 'bridging', l['week'], l['id']))

LESSONS = lesson_list()
lessons_js = ('/* Generated by app/build.py from the lesson files – do not edit by hand.\n'
              '   After adding a lesson, run `python3 app/build.py` and commit this file. */\n'
              'var LESSON_LIST = ' + json.dumps(LESSONS, ensure_ascii=False, indent=1) + ';\n'
              "if (typeof module !== 'undefined') module.exports = LESSON_LIST;\n")
lessons_path = os.path.join(ROOT, 'lessons.js')
if not os.path.exists(lessons_path) or read('lessons.js') != lessons_js:
    open(lessons_path, 'w', encoding='utf-8').write(lessons_js)
    print('Updated lessons.js – commit it so the public site lists every lesson')

# ---- inlining: in the app every page is served on its own, so shared files go inside it ----
SHARED_JS = ['school-calendar.js', 'lessons.js']
def data_uri(name):
    return 'data:image/png;base64,' + base64.b64encode(open(os.path.join(ROOT, 'assets', 'aisa', name), 'rb').read()).decode()
def inline(html):
    for name in SHARED_JS:
        # the public pages may add ?v=N so browsers fetch a fresh copy after a change
        html = re.sub(r'<script src="%s(?:\?v=\d+)?"></script>' % re.escape(name), lambda m: '<script>\n' + read(name) + '</script>', html)
    html = re.sub(r'<link rel="stylesheet" href="site\.css(?:\?v=\d+)?">', lambda m: '<style>\n' + read('site.css') + '</style>', html)
    html = re.sub(r'<link rel="icon"[^>]*>\n?', '', html)              # the app's tab icon is Google's
    return re.sub(r'(src|href)="assets/aisa/([a-z\-]+\.png)"', lambda m: '%s="%s"' % (m[1], data_uri(m[2])), html)

shutil.rmtree(OUT, ignore_errors=True)
shutil.copytree(os.path.join(ROOT, 'app', 'src'), OUT)
# The server uses the same calendar to decide which lessons a student may open.
open(os.path.join(OUT, 'SchoolCalendar.js'), 'w', encoding='utf-8').write(
    '/* Copied by build.py from school-calendar.js – edit that file, not this one. */\n' + read('school-calendar.js'))
# Public lesson pages carry a small "not open yet" check; in the app the server does this.
GATE_RE = re.compile(r'<script src="\.\./school-calendar\.js(?:\?v=\d+)?"></script><script src="\.\./lesson-gate\.js(?:\?v=\d+)?"></script>')
# Google's HtmlService treats '//' in a script as the start of a comment, even inside a
# quoted web address, and cuts the rest of the line ("Invalid or unexpected token").
# Inside every inline script, write '://' as ':\/\/' – the same string to the browser.
# Base64 images inside a script can contain '//' too, so their slashes are escaped the same way.
def protect_script(js):
    js = re.sub(r'data:image/[a-z+]+;base64,[A-Za-z0-9+/=]+', lambda m: m.group(0).replace('/', '\\/'), js)
    return js.replace('://', ':\\/\\/')
def protect_urls(html):
    return re.sub(r'(<script(?![^>]*\bsrc=)[^>]*>)(.*?)(</script>)',
                  lambda m: m.group(1) + protect_script(m.group(2)) + m.group(3), html, flags=re.S | re.I)
def app_page(html):
    return protect_urls(inline(GATE_RE.sub('', html)))
dash = os.path.join(OUT, 'dashboard.html')
dash_html = app_page(open(dash, encoding='utf-8').read())   # read first: opening for writing empties the file
open(dash, 'w', encoding='utf-8').write(dash_html)
bridge = os.path.join(OUT, 'bridge.html')
bridge_html = protect_urls(open(bridge, encoding='utf-8').read().replace('__AISA_MONOGRAM__', data_uri('monogram-white.png')))
open(bridge, 'w', encoding='utf-8').write(bridge_html)
pages = ['index.html', 'calendar.html'] + sorted(glob.glob('grade-*/*.html', root_dir=ROOT))
for p in pages:
    dest = os.path.join(OUT, 'site', p)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    html = read(p)
    if not re.search(r'<head>', html, re.I):
        raise SystemExit(f'{p}: no <head> tag for the sign-in bridge')
    if p.startswith('grade-') and 'LessonHooks' not in html:
        raise SystemExit(f'{p}: missing the LessonHooks line in update() – scores would not be saved')
    open(dest, 'w', encoding='utf-8').write(app_page(html))
open(os.path.join(OUT, 'Catalog.js'), 'w', encoding='utf-8').write(
    '/* Generated by build.py – every lesson on the site. */\nvar CATALOG = ' + json.dumps(LESSONS, ensure_ascii=False, indent=1) + ';\n')

# ---- Private framework data (never committed) ----------------------------
# Put the AI Literacy Scope & Sequence HTML in app/private/ (git-ignored).
# Its framework descriptors and week plan go only into the Apps Script
# project, which lives in the school's Google account.
def parse_framework(path):
    s = open(path, encoding='utf-8').read()
    def txt(x):
        x = re.sub(r'<br\s*/?>', '\n', x)
        return re.sub(r'[ \t\n]+', ' ', H.unescape(re.sub(r'<[^>]+>', ' ', x))).strip()
    def rows(tb):
        return [[txt(c) for c in re.findall(r'<t[hd][^>]*>(.*?)</t[hd]>', r, re.S)] for r in re.findall(r'<tr[^>]*>(.*?)</tr>', tb, re.S)]
    codes = ['CU', 'SD', 'CE', 'GE']
    out = {}
    for g in range(6, 13):
        m = re.search(r'<section class="grade" id="grade-%d".*?</section>' % g, s, re.S)
        if not m: continue
        sec = m.group(0)
        exp = rows(re.search(r'<table class="exp">(.*?)</table>', sec, re.S).group(1))[1:]
        main = rows(re.search(r'<table class="weeks">(.*?)</table>', sec, re.S).group(1))[1:]
        br = re.search(r'<table class="weeks bridge">(.*?)</table>', sec, re.S)
        out[g] = {
            'strands': [{'code': codes[i], 'name': r[0], 'E': r[1], 'P': r[2], 'A': r[3]} for i, r in enumerate(exp[:4])],
            'main': [{'week': r[0], 'lessons': r[1], 'strand': r[2], 'E': r[3], 'P': r[4]} for r in main],
            'bridging': [{'week': r[0], 'lessons': r[1], 'strand': r[2], 'outcome': r[3], 'ref': r[4]} for r in rows(br.group(1))[1:]] if br else []}
    return out

priv = sorted(glob.glob(os.path.join(ROOT, 'app', 'private', '*.html')))
fw = parse_framework(priv[0]) if priv else None
open(os.path.join(OUT, 'Framework.js'), 'w', encoding='utf-8').write(
    '/* Generated by build.py from the private Scope & Sequence – do not commit. */\nvar FRAMEWORK = ' +
    json.dumps(fw, ensure_ascii=False) + ';\n')
print('Framework: ' + (f'{len(fw)} grades from {os.path.basename(priv[0])}' if fw else 'NOT FOUND – put the Scope & Sequence HTML in app/private/ (strand names still work; descriptors will be missing)'))
print(f'Built {len(pages)} pages into app/build/')
