#!/usr/bin/env python3
"""Builds app/build/ for `clasp push`: the Apps Script source plus a copy of
every page of the public site (index, calendar and each lesson)."""
import glob, json, os, re, shutil
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'app', 'build')
shutil.rmtree(OUT, ignore_errors=True)
shutil.copytree(os.path.join(ROOT, 'app', 'src'), OUT)
# school-calendar.js (holidays, breaks and the AI timetable) is a separate file on the
# public site; in the app every page is served on its own, so it is inlined.
CAL_TAG = '<script src="school-calendar.js"></script>'
CAL_JS = '<script>\n' + open(os.path.join(ROOT, 'school-calendar.js'), encoding='utf-8').read() + '</script>'
def inline_calendar(html):
    return html.replace(CAL_TAG, CAL_JS)
# The server uses the same calendar to decide which lessons a student may open.
open(os.path.join(OUT, 'SchoolCalendar.js'), 'w', encoding='utf-8').write(
    '/* Copied by build.py from school-calendar.js – edit that file, not this one. */\n' +
    open(os.path.join(ROOT, 'school-calendar.js'), encoding='utf-8').read())
# Public lesson pages carry a small "not open yet" check; in the app the server does this.
GATE_TAG = '<script src="../school-calendar.js"></script><script src="../lesson-gate.js"></script>'
dash = os.path.join(OUT, 'dashboard.html')
dash_html = inline_calendar(open(dash, encoding='utf-8').read())
open(dash, 'w', encoding='utf-8').write(dash_html)
catalog = []
pages = ['index.html', 'calendar.html'] + sorted(glob.glob('grade-*/*.html', root_dir=ROOT))
for p in pages:
    dest = os.path.join(OUT, 'site', p)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    html = open(os.path.join(ROOT, p), encoding='utf-8').read()
    if not re.search(r'<head>', html, re.I):
        raise SystemExit(f'{p}: no <head> tag for the sign-in bridge')
    if p.startswith('grade-') and 'LessonHooks' not in html:
        raise SystemExit(f'{p}: missing the LessonHooks line in update() – scores would not be saved')
    open(dest, 'w', encoding='utf-8').write(inline_calendar(html.replace(GATE_TAG, '')))
    m = re.match(r'grade-(\d+)/(main|bridging)-w(\d+)', p)
    if m:
        t = re.search(r'<title>([^<]*)</title>', html)
        catalog.append({'id': p[:-5], 'grade': int(m[1]), 'course': m[2], 'week': int(m[3]),
                        'title': re.sub(r'\s+–\s+Grade.*$', '', t[1]) if t else p,
                        'activities': len(re.findall(r'^ \{id:"', html, re.M))})
open(os.path.join(OUT, 'Catalog.js'), 'w', encoding='utf-8').write(
    '/* Generated by build.py – every lesson on the site. */\nvar CATALOG = ' + json.dumps(catalog, ensure_ascii=False, indent=1) + ';\n')

# ---- Private framework data (never committed) ----------------------------
# Put the AI Literacy Scope & Sequence HTML in app/private/ (git-ignored).
# Its framework descriptors and week plan go only into the Apps Script
# project, which lives in the school's Google account.
def parse_framework(path):
    import html as H
    s = open(path, encoding='utf-8').read()
    def txt(x):
        x = re.sub(r'<br\s*/?>', '\n', x)
        return re.sub(r'[ \t\n]+', ' ', H.unescape(re.sub(r'<[^>]+>', ' ', x))).strip()
    def rows(tb):
        return [[txt(c) for c in re.findall(r'<t[hd][^>]*>(.*?)</t[hd]>', r, re.S)] for r in re.findall(r'<tr[^>]*>(.*?)</tr>', tb, re.S)]
    codes = ['CU', 'SD', 'CE', 'GE']
    out = {}
    for g in range(6, 13):
        m = re.search(r'<section class="grade" id="grade-%d".*?</section>' % g, s, re.S)
        if not m: continue
        sec = m.group(0)
        exp = rows(re.search(r'<table class="exp">(.*?)</table>', sec, re.S).group(1))[1:]
        main = rows(re.search(r'<table class="weeks">(.*?)</table>', sec, re.S).group(1))[1:]
        br = re.search(r'<table class="weeks bridge">(.*?)</table>', sec, re.S)
        out[g] = {
            'strands': [{'code': codes[i], 'name': r[0], 'E': r[1], 'P': r[2], 'A': r[3]} for i, r in enumerate(exp[:4])],
            'main': [{'week': r[0], 'lessons': r[1], 'strand': r[2], 'E': r[3], 'P': r[4]} for r in main],
            'bridging': [{'week': r[0], 'lessons': r[1], 'strand': r[2], 'outcome': r[3], 'ref': r[4]} for r in rows(br.group(1))[1:]] if br else []}
    return out

priv = sorted(glob.glob(os.path.join(ROOT, 'app', 'private', '*.html')))
fw = parse_framework(priv[0]) if priv else None
open(os.path.join(OUT, 'Framework.js'), 'w', encoding='utf-8').write(
    '/* Generated by build.py from the private Scope & Sequence – do not commit. */\nvar FRAMEWORK = ' +
    json.dumps(fw, ensure_ascii=False) + ';\n')
print('Framework: ' + (f'{len(fw)} grades from {os.path.basename(priv[0])}' if fw else 'NOT FOUND – put the Scope & Sequence HTML in app/private/ (strand names still work; descriptors will be missing)'))
print(f'Built {len(pages)} pages into app/build/')
